os: linux
dist: xenial
language: php
php:
  - 8.0
  - 7.4
  - 7.3

env:
  global:
    - DB=sqlite
    - PHP_COVERAGE=FALSE
    - PATCH_VERSION_CHECK=FALSE
    - OCC_CHECK_CODE=FALSE
  jobs:
    - "SERVER_BRANCH=master PHP_COVERAGE=TRUE"
    - "SERVER_BRANCH=stable21 OCC_CHECK_CODE=TRUE"

branches:
  only:
    - master
    - "/^stable\\d+(\\.\\d+)?$/"
    - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

cache:
  directories:
    - "$HOME/.composer/cache/files"
    - "$HOME/.npm"
    - "$HOME/.cache/bower"

before_install:
  # XDebug is only needed if we report coverage -> speeds up other builds (7.3 has no xdebug yet)
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini || true; fi

  - if ! php -m | grep '^zip$' >/dev/null; then echo "extension=zip" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer self-update
  - composer install
  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $SERVER_BRANCH core
  - if [[ "$PATCH_VERSION_CHECK" = "TRUE" ]]; then echo "<?php" > core/lib/versioncheck.php; fi
  - if [[ "$PATCH_VERSION_CHECK" = "TRUE" ]]; then  sed -ri 's/(<php min\-version="[0-9\.]+") max\-version="[0-9\.]+"/\1/g' twofactor_gateway/appinfo/info.xml; fi
  - mv twofactor_gateway core/apps/

before_script:
  # Set up core
  - php -f core/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database "$DB" --database-pass=''

  # Set up app
  - php -f core/occ app:enable twofactor_gateway

  - cd core/apps/twofactor_gateway

script:
  # Check PHP syntax errors
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run server's app code checker (will be removed in NC 23)
  - if [[ "$OCC_CHECK_CODE" = "TRUE" ]]; then php ../../occ app:check-code twofactor_gateway; fi

  # Run PHP tests
  - composer run test:unit:dev

after_script:
  # Upload coverage report to Scrutinizer
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml; fi

jobs:
  include:
    # NC20 with PHP 7.2
    - php: 7.2
      dist: trusty
      env: "SERVER_BRANCH=stable20 OCC_CHECK_CODE=TRUE"
    # NC22 with PHP nightly
    - php: nightly
      env: "SERVER_BRANCH=master PATCH_VERSION_CHECK=TRUE"
  fast_finish: true
  allow_failures:
    - php: nightly
